name: sit2-mob

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/akamai-nonprod-sit2-pdp-mob.yml'
      - 'SIT2_PDP_MOBILE/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: sit2-mob

    steps:
      - name: Checkout
        uses: actions/checkout@v2
