name: sit2-pdp

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/akamai-nonprod-sit2-pdp-dt.yml'
      - 'SIT2_PDP/*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: sit2-pdp

    steps:
      - name: Checkout
        uses: actions/checkout@v2
