name: terraform-plan

on:
  push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: terraform plan

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest Azure CLI
        run: curl -skL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: terraform plan
        uses: dflook/terraform-plan@v1
