name: terraform-plan

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_azuread_application_id: ${{ secrets.AZURE_CLIENT_ID }}
  TF_VAR_azuread_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: terraform plan

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure CLI script
        run: which az

      - name: terraform plan
        uses: dflook/terraform-plan@v1
